### ISSUE TITLE
Data download crashes in some point

### ISSUE THREAD

**Issue by arnal46** [mhmcc/dunnart-neural-activity#1] opened 2023-05-29 15:58 UTC
Hi,

First of all, thank you for sharing the code.

Secondly, I'd like to mention that I encountered difficulties downloading the entire dataset you provided. It appears to be quite large, resulting in slow download speeds, and eventually, the download crashes after a certain point. It indicates that it would take more than 2 days to complete the download.

Is it possible for you to share a smaller dataset instead? This would be helpful for me to understand the required format of the Excel file and allow me to test how it works, anf if it needs other files. 

Thank you once again, and I look forward to your response.

A screen-capture :

![imagen](https://github.com/mhmcc/dunnart-neural-activity/assets/25934723/3475e862-9af3-48a6-9f68-4ae5d6812458)

**Comment by mhmcc** [comment] 2023-05-30 02:26
Hi @arnal46,

Thank you for your message.

I am sorry to hear that you are having issues with the download. However, I can confirm that I downloaded the files in approximately 1 hour today. I have also checked with colleagues in other parts of the world and they were able to download the data without any issues in 2-3 hours. Perhaps try again at another time.

The Excel file included in the dataset is a lookup table that contains metadata for each of the imaging files. It does not include the experimental data. The complete data set linked in the README is required to run the analysis as published.

Please also note that the files are only 13.9GB in total, which is relatively modest in size compared with many neuroimaging datasets.

I am closing this issue because:
- It relates to downloading data from an external server, not an issue with the code.
- I do not maintain this external server but have confirmed that the download is working at this time.

**Closed as not planned by mhmcc** 2023-05-30 02:26 UTC
